### ISSUE TITLE
Support for Continue Train

### ISSUE THREAD

**Issue by felixnext** [microsoft/lightgbm-transform#18]
The lightgbm framework allows to continue training from a previous model using the `init_model` parameter
([docs here](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html)).

Since we often want to fine-tune rankers to accommodate for seasonal effects, this is a critical feature for us.

**Comment by chjinche** [comment]
@felixnext Thanks for opening the issue! Could you please share a small repro sample and error message you met when you tried continue train combining with transform? This will help clarify the unsupported scenario quickly.

**Comment by ltxtech1999** [comment]
Hi,@felixnext, thanks for asking. We add a test to confirm that we support continue training. You can follow [our example](https://github.com/microsoft/lightgbm-transform/pull/19) to use continue_train feature. 
- We set num_trees = 10 in the first bst training, which means the number of boosting iteration round is 10 in the example, so the current_iteration is 10.
- Then we use continue_train, and set 20 as the training round, and finally we could see the current_iteration is 30, and it proves continue_train feature works well.
